language: java

# avoid double builds on pull requests
branches:
  only:
    - master
    -
jobs:
  include:
    # build + test
    - stage: Build + test
      name: Linux OpenJDK 10
      os: linux
      dist: trusty
      jdk: openjdk10
      script: mvn clean package
    - stage: Build + test
      name: Linux OpenJDK 11
      os: linux
      dist: trusty
      jdk: openjdk11
    - stage: Build + test
      name: Linux Oracle JDK 11
      os: linux
      dist: trusty
      jdk: oraclejdk11