language: java

# avoid double builds on pull requests
branches:
  only:
    - master

jobs:
  include:
    # build + test
    - stage: Build + test
      name: Linux OpenJDK 11
      os: linux
      dist: trusty
      jdk: openjdk11
    - stage: Build + test
      name: Linux OpenJDK 12
      os: linux
      dist: trusty
      jdk: openjdk12
    - stage: Build + test
      name: Linux OpenJDK 13
      os: linux
      dist: trusty
      jdk: openjdk13
